version: '3'
services:
  client:
    build: ./client/
    volumes:
      - ./client/src:/usr/local/app/src
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    build: ./server/
    volumes:
      - ./server/src:/usr/local/app/src
    ports:
      - "3001:3001"
